name: Deploy a docker image to K8

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  EKS_CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME }}

jobs:
  deploy-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    environment: dev
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup EKS
        run: |
          aws eks --region  ${{ secrets.AWS_REGION }} update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }}

      - name: Push image to kubernetes cluster
        shell: bash
        run: |
          chmod +x ./eks-deploy-script.sh 
              ./eks-deploy-script.sh

      - name: K8s deployments
        run: |
          kubectl get deployments -n blog
